using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Numerics;
using System.Reflection;
using System.Runtime.InteropServices;
using AnoMech.Helpers;
using AnoMech.Pointers;
using Dalamud.Game.Addon.Lifecycle;
using Dalamud.Game.Addon.Lifecycle.AddonArgTypes;
using Dalamud.Game.ClientState.Conditions;
using Dalamud.Hooking;
using FFXIVClientStructs.FFXIV.Client.Game;
using FFXIVClientStructs.FFXIV.Client.Game.Character;
using FFXIVClientStructs.FFXIV.Client.Game.Event;
using FFXIVClientStructs.FFXIV.Client.Game.UI;
using FFXIVClientStructs.FFXIV.Client.Graphics.Environment;
using FFXIVClientStructs.FFXIV.Client.Graphics.Scene;
using FFXIVClientStructs.FFXIV.Client.Network;
using FFXIVClientStructs.FFXIV.Client.UI.Agent;
using Lumina.Excel.Sheets;
using static FFXIVClientStructs.FFXIV.Client.Network.PacketDispatcher.Delegates;
using ThreadingTask = System.Threading.Tasks.Task;

namespace AnoMech.Core.Map;

// Client-side zone loading and packet firewall. Ported from Hyperborea (Memory.cs
// + Utils.cs). Must be in the Inn before calling Enter(); Leave() reloads the inn.
// All public methods must be called from the framework thread. The start gate and the
// stay's integrity watch are in ZoneSession.Guard.cs.
public sealed unsafe partial class ZoneSession : IDisposable
{
    private class SessionSave
    {
        public uint TerritoryId { get; set; }
        public Vector3 Position { get; set; }
        public float Rotation { get; set; }
        public int Exp { get; set; }
        public uint RestedExp { get; set; }
        public bool LevelSync { get; set; }
        public int Level { get; set; }
        public bool ItemLevelSync { get; set; }
        public Dictionary<int, int> Attributes { get; } = new();
    }

    // TerritoryIntendedUse.Inn = 2 (from ECommons TerritoryIntendedUseEnum)
    private const uint InnIntendedUse = 2;

    // ── Native delegates ──────────────────────────────────────────────────────

    private delegate byte SendPacketDelegate(nint a1, nint a2, nint a3, byte a4);
    private readonly Hook<SendPacketDelegate> sendPacketHook;

    // OnReceivePacket delegate type generated by FFXIVClientStructs from [VirtualFunction(1)]
    private readonly Hook<OnReceivePacket> receivePacketHook;
    // Captured from the first packet that passes the hook; InjectIncomingPacket needs it.
    private PacketDispatcher* dispatcher;

    // The highest GlobalSequence seen on real action-effect packets this session: a replayed
    // effect packet has to carry a counter above everything the client already processed, or it
    // reads as stale. Opcodes are this client build's (see UmadRealPackets).
    public uint MaxActionEffectCounter { get; private set; }
    private const ushort ActionEffect1Opcode = 0x0371;
    private const ushort ActionEffect8Opcode = 0x03C8;

    // ── State ─────────────────────────────────────────────────────────────────

    private readonly ushort heartbeatOpcode;
    private uint? loadedInstanceContent;

    // Set true right before we open the Social window for a party resync; the Social
    // PostSetup listener closes it again and clears this. Distinguishes our open from
    // a manual one so manual opens aren't auto-closed.
    private bool autoCloseSocial;

    public bool IsActive { get; private set; }

    // Set when Enter moved Dalamud's TerritoryType to the sim zone; Revert moves it back.
    private bool clientTerritorySynced;

    private readonly SessionSave sessionSave = new();

    // ── Construction ──────────────────────────────────────────────────────────

    public ZoneSession()
    {
        // Heartbeat (ZoneUp) opcode — auto-detected by signature (from Hyperborea Memory.cs)
        heartbeatOpcode = (ushort)Marshal.ReadInt32(
            Plugin.SigScanner.ScanText("C7 44 24 ?? ?? ?? ?? ?? 48 F7 F1") + 0x4);
        Plugin.Log.Information($"[ZoneSession] Heartbeat opcode: {heartbeatOpcode}");

        // Send-packet hook (sig from Hyperborea Memory.cs)
        var sendAddr = Plugin.SigScanner.ScanText(
            "48 89 5C 24 ?? 48 89 74 24 ?? 4C 89 64 24 ?? 55 41 56 41 57 48 8B EC 48 83 EC 70");
        sendPacketHook = Plugin.GameInterop.HookFromAddress<SendPacketDelegate>(
            sendAddr, SendPacketDetour);

        // Receive-packet hook — address from PacketDispatcher.StaticVirtualTablePointer->OnReceivePacket.
        // This is the standard approach used by ECommons/Dalamud's GameNetwork service.
        // PacketDispatcher.Delegates.OnReceivePacket and StaticVirtualTablePointer are generated by
        // FFXIVClientStructs from [VirtualFunction(1)] + [VirtualTable] on PacketDispatcher.
        var receiveAddr = (nint)PacketDispatcher.StaticVirtualTablePointer->OnReceivePacket;
        Plugin.Log.Information($"[ZoneSession] OnReceivePacket: {receiveAddr:X}");
        receivePacketHook = Plugin.GameInterop.HookFromAddress<OnReceivePacket>(
            receiveAddr, ReceivePacketDetour);

        Plugin.AddonLifecycle.RegisterListener(AddonEvent.PostSetup, "Social", OnSocialPostSetup);

        Current = this;
        Plugin.Log.Information("[ZoneSession] Initialized.");
    }

    // ── Public API ────────────────────────────────────────────────────────────

    public static bool IsInInn()
    {
        var row = Plugin.DataManager.GetExcelSheet<TerritoryType>()
            ?.GetRowOrDefault(Plugin.ClientState.TerritoryType);
        return row?.TerritoryIntendedUse.RowId == InnIntendedUse;
    }

    // Any state in which the local player can't freely act, or the server is about to act on
    // (a cast, a queue, a pending world visit): a start there lands while the firewall hides
    // the outcome.
    public static bool IsPlayerBusy()
    {
        var c = Plugin.Condition;
        return c[ConditionFlag.WatchingCutscene]
            || c[ConditionFlag.WatchingCutscene78]
            || c[ConditionFlag.OccupiedInCutSceneEvent]
            || c[ConditionFlag.OccupiedInEvent]
            || c[ConditionFlag.OccupiedInQuestEvent]
            || c[ConditionFlag.OccupiedSummoningBell]
            || c[ConditionFlag.Occupied30]
            || c[ConditionFlag.Occupied33]
            || c[ConditionFlag.Occupied38]
            || c[ConditionFlag.Occupied39]
            || c[ConditionFlag.Crafting]
            || c[ConditionFlag.ExecutingCraftingAction]
            || c[ConditionFlag.PreparingToCraft]
            || c[ConditionFlag.MeldingMateria]
            || c[ConditionFlag.Gathering]
            || c[ConditionFlag.ExecutingGatheringAction]
            || c[ConditionFlag.Fishing]
            || c[ConditionFlag.TradeOpen]
            || c[ConditionFlag.BetweenAreas]
            || c[ConditionFlag.BetweenAreas51]
            || c[ConditionFlag.LoggingOut]
            || c[ConditionFlag.SystemError]
            || c[ConditionFlag.Casting]
            || c[ConditionFlag.Casting87]
            || c[ConditionFlag.Unconscious]
            || c[ConditionFlag.InCombat]
            || c[ConditionFlag.BoundByDuty]
            || c[ConditionFlag.BoundByDuty56]
            || c[ConditionFlag.BoundByDuty95]
            || c[ConditionFlag.WaitingForDutyFinder]
            || c[ConditionFlag.WaitingForDuty]
            || c[ConditionFlag.InDutyQueue]
            || c[ConditionFlag.DutyRecorderPlayback]
            || c[ConditionFlag.InDeepDungeon]
            || c[ConditionFlag.ReadyingVisitOtherWorld]
            || c[ConditionFlag.WaitingToVisitOtherWorld]
            || c[ConditionFlag.RegisteringForRaceOrMatch]
            || c[ConditionFlag.WaitingForRaceOrMatch]
            || c[ConditionFlag.RegisteringForTripleTriadMatch]
            || c[ConditionFlag.WaitingForTripleTriadMatch]
            || c[ConditionFlag.WaitingForTripleTriadMatch83]
            || c[ConditionFlag.ChocoboRacing]
            || c[ConditionFlag.PlayingMiniGame]
            || c[ConditionFlag.PlayingLordOfVerminion]
            || c[ConditionFlag.ParticipatingInCustomMatch]
            || c[ConditionFlag.Performing]
            || c[ConditionFlag.Mounted]
            || c[ConditionFlag.Mounting]
            || c[ConditionFlag.Mounting71]
            || c[ConditionFlag.MountOrOrnamentTransition]
            || c[ConditionFlag.MountImmobile]
            || c[ConditionFlag.RidingPillion]
            || c[ConditionFlag.InFlight]
            || c[ConditionFlag.UsingChocoboTaxi]
            || c[ConditionFlag.OperatingSiegeMachine]
            || c[ConditionFlag.PilotingMech]
            || c[ConditionFlag.CarryingObject]
            || c[ConditionFlag.CarryingItem]
            || c[ConditionFlag.BeingMoved]
            || c[ConditionFlag.Swimming]
            || c[ConditionFlag.Diving]
            || c[ConditionFlag.Jumping]
            || c[ConditionFlag.Jumping61]
            || c[ConditionFlag.Occupied];
    }

    // Load the target territory, teleport player to playerSpawn, enable firewall. Firewall is
    // enabled before the zone load (matching Hyperborea's sequence). False when the start is
    // refused or the firewall didn't arm; nothing is loaded then.
    public bool Enter(uint territoryId, Vector3 playerSpawn, byte levelSync, ushort itemLevelSync)
    {
        if (StartBlockedReason() is { } blocked)
        {
            AnoMech.Core.DiagnosticLog.Warn($"[ZoneGuard] Enter refused: {blocked}.");
            return false;
        }
        var localPlayer = Plugin.ObjectTable.LocalPlayer!;

        sessionSave.TerritoryId = Plugin.ClientState.TerritoryType;
        sessionSave.Position = localPlayer.Position;
        sessionSave.Rotation = localPlayer.Rotation;
        sessionSave.Exp = Plugin.PlayerState.GetClassJobExperience(Plugin.PlayerState.ClassJob.Value);
        sessionSave.RestedExp = Plugin.PlayerState.BaseRestedExperience;
        sessionSave.LevelSync = levelSync != 0;
        sessionSave.Level = localPlayer.Level;
        sessionSave.ItemLevelSync = itemLevelSync != 0;
        sessionSave.Attributes.Clear();

        EnableFirewall();
        if (!FirewallArmed(out var why))
        {
            // Half up with no session, nothing would ever release what it holds.
            if (!DisableFirewall()) Die($"{why}, and the half-armed firewall would not come back down");
            AnoMech.Core.DiagnosticLog.Warn($"[ZoneGuard] Enter refused: {why}.");
            return false;
        }
        CaptureInnState();
        try
        {
            LoadZoneInternal(territoryId, false, playerSpawn);
        }
        catch (Exception e)
        {
            // Part-way into the load with the firewall up: back out through the verified revert,
            // or nothing would ever lift the firewall.
            AnoMech.Core.DiagnosticLog.Warn($"[ZoneGuard] Enter: the zone load threw -- reverting to the inn. {e}");
            IsActive = true;
            ArmGuard(territoryId);
            Revert(false);
            return false;
        }
        IsActive = true;
        ArmGuard(territoryId);
        // After ArmGuard, which records Dalamud's reading as the inn to return to.
        if (Plugin.Config.SplatoonCompat)
        {
            clientTerritorySynced = TrySetClientTerritory(territoryId);
            AnoMech.Core.DiagnosticLog.Info($"[ZoneSession] Dalamud territory {(clientTerritorySynced ? "now reads" : "could not be set to")} {territoryId}.");
        }
        Plugin.Log.Information($"[ZoneSession] Entered territory {territoryId}.");
        return true;
    }

    // Immediately set the active weather. Must be called on the framework thread. weatherId is
    // a Weather-sheet row; transition is the fade time in seconds.
    //
    // SKY-TINT ONLY. Every WeatherManager write tried (SetNextWeather with either override flag)
    // leaked out of the sim and survived the inn reload. EnvManager.ActiveWeather is a per-zone
    // render field the reload resets on its own. Do NOT reintroduce a WeatherManager write.
    public void SetWeather(byte weatherId, float transition = 0.5f)
    {
        // Nothing may touch the environment outside a session: a stray write (a replayed
        // SetWeatherMessage after a Leave) would permanently alter the open-world sky.
        if (!IsActive) return;
        desiredWeather = weatherId;
        desiredTransition = transition;
        var env = EnvManager.Instance();
        if (env == null) return;
        env->ActiveWeather = weatherId;
        env->TransitionTime = transition;
        weatherAppliedMs = Environment.TickCount64;
        StartWeatherDiagnostic(weatherId);
    }

    // The weather this session wants, re-applied by TickWeather when the zone load resets it:
    // the engine zeroes ActiveWeather as the environment scene comes up, and a write on a fixed
    // delay lost that race whenever the load ran long (a quick switch between territories).
    private byte? desiredWeather;
    private float desiredTransition;
    private long? weatherAppliedMs;
    private const long WeatherSettleMs = 3000;

    private void ReassertWeather()
    {
        if (desiredWeather is not { } wanted) return;
        var env = EnvManager.Instance();
        if (env == null || env->EnvScene == null) return;
        if (weatherAppliedMs is { } applied)
        {
            var settling = Environment.TickCount64 - applied < WeatherSettleMs;
            if (env->ActiveWeather == wanted || (env->ActiveWeather != 0 && !settling)) return;
            AnoMech.Core.DiagnosticLog.Info($"[ZoneSession] Weather {env->ActiveWeather} where {wanted} was set -- re-applying.");
        }
        SetWeather(wanted, desiredTransition);
    }

    // Read-only weather investigation: logs EnvManager/WeatherManager state at fixed checkpoints
    // after a SetWeather, out to 10s, plus a byte diff of EnvState/EnvSimulator against their
    // checkpoint-0 baseline. No WeatherManager writes.
    private long? weatherDiagStartMs;
    private byte weatherDiagTarget;
    private int weatherDiagNextIndex;
    private byte[]? envStateSnapshot;
    private byte[]? envSimulatorSnapshot;
    private static readonly int[] WeatherDiagCheckpointsMs = [0, 250, 500, 750, 1000, 1500, 2000, 3000, 5000, 7000, 10000];

    // Candidate fog/view-distance offsets found by that diff: both climb from 1000 to 1800 during
    // the "red haze, then clears up" window and are duplicated across the two structs. Unlabeled
    // in FFXIVClientStructs; a hypothesis. Re-asserted every frame because the native transition
    // climbs them back on its own.
    private const int EnvStateFogOffset = 0xD8;
    private const int EnvSimulatorFogOffset = 0x2F8;

    // The value both fog fields are held at every frame while non-null (TickWeather); null =
    // the engine's own transition. Set per phase through TargetInstance.FogHold by
    // MapController.TryLoad, never globally: only Umad P1 wants its pre-transition haze kept.
    public float? FogHold { get; set; }

    private void StartWeatherDiagnostic(byte weatherId)
    {
        weatherDiagStartMs = Environment.TickCount64;
        weatherDiagTarget = weatherId;
        weatherDiagNextIndex = 0;
        envStateSnapshot = null;
        envSimulatorSnapshot = null;
        LogWeatherDiagnostic(0);
        weatherDiagNextIndex = 1;
    }

    // Framework-thread, every frame while IsActive (driven by MapController.Tick).
    public void TickWeather()
    {
        if (!IsActive) return;
        ReassertWeather();
        if (FogHold is { } hold)
        {
            var env = EnvManager.Instance();
            if (env != null)
            {
                *(float*)((byte*)&env->EnvState + EnvStateFogOffset) = hold;
                *(float*)((byte*)&env->EnvSimulator + EnvSimulatorFogOffset) = hold;
            }
        }

        if (weatherDiagStartMs is not { } start) return;
        var elapsedMs = Environment.TickCount64 - start;
        while (weatherDiagNextIndex < WeatherDiagCheckpointsMs.Length && elapsedMs >= WeatherDiagCheckpointsMs[weatherDiagNextIndex])
        {
            LogWeatherDiagnostic(WeatherDiagCheckpointsMs[weatherDiagNextIndex]);
            weatherDiagNextIndex++;
        }
        if (weatherDiagNextIndex >= WeatherDiagCheckpointsMs.Length) weatherDiagStartMs = null;
    }

    private void LogWeatherDiagnostic(int checkpointMs)
    {
        var env = EnvManager.Instance();
        var mgr = WeatherManager.Instance();
        var envActive = env != null ? env->ActiveWeather : (byte)255;
        var envPtr = (nint)env;
        var mgrCurrent = mgr != null ? mgr->GetCurrentWeather() : (byte)255;
        var mgrWeatherId = mgr != null ? mgr->WeatherId : (byte)255;
        var mgrOverride = mgr != null ? mgr->WeatherOverride : (byte)255;
        var slotInfo = "n/a";
        if (mgr != null && mgr->WeatherIndex < mgr->Weathers.Length)
        {
            var sw = mgr->Weathers[mgr->WeatherIndex];
            slotInfo = $"slot[{mgr->WeatherIndex}] Current={sw.CurrentWeatherId} Next={sw.NextWeatherId} ForcedCurrent={sw.IsCurrentWeatherForced} ForcedNext={sw.IsNextWeatherForced}";
        }
        // EnvScene._weatherIds (32 bytes): the zone's own per-EnvSpace weather table, a local
        // position-resolved source of the silent ActiveWeather reassert.
        var scenePtr = (nint)(env != null ? env->EnvScene : null);
        var weatherIdsInfo = "n/a";
        if (env != null && env->EnvScene != null)
        {
            var ids = new byte[32];
            var raw = (byte*)env->EnvScene + 0x30;
            for (var i = 0; i < 32; i++) ids[i] = raw[i];
            weatherIdsInfo = string.Join(",", ids);
        }
        // EnvManager.EnvSpace is the active trigger volume, resolved from the player's position
        // against the zone's layout; logged with the position so a revert can be tied to it.
        var envSpacePtr = (nint)(env != null ? env->EnvSpace : null);
        var envLocationPtr = (nint)(env != null && env->EnvSpace != null ? env->EnvSpace->EnvLocation : null);
        var locationCount = env != null && env->EnvScene != null ? env->EnvScene->LocationCount : 0u;
        var playerPos = Plugin.ObjectTable.LocalPlayer?.Position;
        var posInfo = playerPos is { } p ? $"{p.X:F2},{p.Y:F2},{p.Z:F2}" : "n/a";
        AnoMech.Core.DiagnosticLog.Info(
            $"[ZoneSession] WeatherDiag +{checkpointMs,5}ms target={weatherDiagTarget} -- EnvManager(0x{envPtr:X}).ActiveWeather={envActive} "
            + $"WeatherManager.GetCurrentWeather={mgrCurrent} WeatherId={mgrWeatherId} WeatherOverride={mgrOverride} {slotInfo} "
            + $"EnvScene(0x{scenePtr:X})._weatherIds=[{weatherIdsInfo}] "
            + $"EnvSpace=0x{envSpacePtr:X} EnvLocation=0x{envLocationPtr:X} LocationCount={locationCount} PlayerPos=({posInfo}).");

        // EnvState/EnvSimulator are barely documented, so every byte is snapshotted at
        // checkpoint 0 and only the words that differ are logged afterwards.
        if (env != null)
        {
            LogStructDiff("EnvState", (byte*)&env->EnvState, sizeof(EnvState), ref envStateSnapshot, checkpointMs);
            LogStructDiff("EnvSimulator", (byte*)&env->EnvSimulator, sizeof(EnvSimulator), ref envSimulatorSnapshot, checkpointMs);
        }
    }

    private static void LogStructDiff(string label, byte* current, int size, ref byte[]? snapshot, int checkpointMs)
    {
        if (snapshot == null)
        {
            snapshot = new byte[size];
            Marshal.Copy((nint)current, snapshot, 0, size);
            return;
        }
        var changes = new List<string>();
        for (var i = 0; i + 4 <= size; i += 4)
        {
            var oldVal = (uint)(snapshot[i] | (snapshot[i + 1] << 8) | (snapshot[i + 2] << 16) | (snapshot[i + 3] << 24));
            var newVal = *(uint*)(current + i);
            if (oldVal == newVal) continue;
            var oldF = *(float*)&oldVal;
            var newF = *(float*)&newVal;
            changes.Add($"+0x{i:X}: 0x{oldVal:X8}({oldF:F3}) -> 0x{newVal:X8}({newF:F3})");
        }
        if (changes.Count > 0)
            AnoMech.Core.DiagnosticLog.Info($"[ZoneSession] WeatherDiag +{checkpointMs,5}ms {label} changed vs t=0: {string.Join("; ", changes)}.");
    }

    // Weather for a fresh zone load: written once the environment scene exists (ReassertWeather).
    public void ApplyWeather(byte weatherId)
    {
        desiredWeather = weatherId;
        desiredTransition = 0.5f;
        weatherAppliedMs = null;
    }

    // Reload the saved inn territory and restore position; disable firewall.
    public void Revert(bool dispose)
    {
        // A tripped stay never reaches the inn reload: the client would be shown a zone the
        // server doesn't have it in.
        if (tripReason is { } tripped) Die(tripped);
        // Outside a session sessionSave is stale: the delayed position re-assert would move the
        // real character with the firewall down.
        if (!IsActive) return;
        if (guardArmed) AnoMech.Core.DiagnosticLog.Info(StateSnapshot($"revert starting (dispose={dispose})"));

        // We need to wait before calling DisableFirewall(), so we'll set the Occupied condition to be sure the Player doesn't do anything in the meantime.
        var condition = Conditions.Instance();
        condition->Occupied = true;

        weatherDiagStartMs = null; // stop the diagnostic before the inn's own weather loads
        envStateSnapshot = null;
        envSimulatorSnapshot = null;
        desiredWeather = null;
        weatherAppliedMs = null;
        FogHold = null; // stop re-asserting the fog hold before the inn's own value loads

        // The firewall lift requires Dalamud to read the inn again.
        if (clientTerritorySynced)
        {
            clientTerritorySynced = false;
            if (!TrySetClientTerritory(innClientTerritory))
                AnoMech.Core.DiagnosticLog.Warn($"[ZoneSession] Dalamud territory could not be restored to the inn ({innClientTerritory}).");
        }

        // The reload can throw; the firewall and the Occupied flag must be released regardless,
        // or the client is left unable to send anything until the plugin is unloaded.
        try
        {
            if (sessionSave.TerritoryId != 0)
                LoadZoneInternal(sessionSave.TerritoryId, true, sessionSave.Position, sessionSave.Rotation);
        }
        catch (Exception e)
        {
            Plugin.Log.Error($"[ZoneSession] Revert: the inn reload threw -- releasing the firewall anyway. {e}");
        }

        sessionSave.TerritoryId = 0;

        IsActive = false;
        Plugin.Log.Information("[ZoneSession] Reverted to inn.");
        LogStaySummary();
        if (guardArmed) AnoMech.Core.DiagnosticLog.Info(StateSnapshot("inn reload done"));

        // If this is getting called on Dispose(), then these Tasks will not be properly executed, so we'll gate them to be safe
        if (!dispose)
        {
            // If this isn't delayed, a Packet will be sent to the server!!!
            var savedPosition = sessionSave.Position;
            var savedRotation = sessionSave.Rotation;
            var stay = stayId;
            ThreadingTask.Delay(1000).ContinueWith(_ => Plugin.Framework.Run(() =>
            {
                // Already lifted (an unload during the wait), or a later stay owns the character
                // (Enter refuses while this is pending, so only a bypass gets here): a restore now
                // would move the character with nothing holding the move.
                if (stay != stayId || !guardArmed) return;
                // A throw here must not strand the stay: the lift below verifies the position itself.
                try
                {
                    RestoreBeforeLift(savedPosition, savedRotation);
                }
                catch (Exception e)
                {
                    AnoMech.Core.DiagnosticLog.Warn($"[ZoneGuard] The restore before the lift threw: {e}");
                }
                ReleasePlayerConditions();
                LiftFirewallOrDie("after the inn reload");
            }));

            // Resync the real party HUD once the inn reload has settled. A bare
            // InfoProxyPartyMember.RequestData() sends the same request the Social window
            // does but doesn't sync MainGroup — the HUD update is client-side work the
            // Social agent does on the reply (proven via packet trace). So open the Social
            // agent and let it do that work itself. (Closing it again is a follow-up step.)
            ThreadingTask.Delay(1500).ContinueWith(_ => Plugin.Framework.Run(OpenSocialForPartyResync));
        }
        else
        {
            // This skips all safety delays, so if possible, don't disable the plugin while being in a Scenario
            SetLocalPlayerPosition(sessionSave.Position, sessionSave.Rotation);
            ReleasePlayerConditions();
            LiftFirewallOrDie("on plugin unload", mayRetry: false);
            Plugin.Framework.Run(OpenSocialForPartyResync);
        }
    }

    private void RestoreBeforeLift(Vector3 savedPosition, float savedRotation)
    {
        // The Player could do something like jump, so to be extremely sure we are where we are supposed to, we set the Position and Rotation again.
        var beforeRestore = Plugin.ObjectTable.LocalPlayer?.Position;
        SetLocalPlayerPosition(savedPosition, savedRotation);
        var afterRestore = Plugin.ObjectTable.LocalPlayer?.Position;
        AnoMech.Core.DiagnosticLog.Info($"[ZoneGuard] Position re-asserted to {savedPosition.X:F2},{savedPosition.Y:F2},{savedPosition.Z:F2}: was {Describe(beforeRestore)}, now {Describe(afterRestore)}.");
    }

    // What the settle and the sim hold on the character: Occupied for the settle, and the
    // afflictions and untargetable state Suppression leaves. Every lift path releases them, and
    // none may be kept from its lift by a throw here.
    private static void ReleasePlayerConditions()
    {
        var condition = Conditions.Instance();
        condition->Occupied = false;

        // TODO: this is here because of Suppression. Either define it as normal behaviour, or add an OnLeave method on Scenarios
        condition->SufferingStatusAffliction = false;
        condition->SufferingStatusAffliction2 = false;

        try
        {
            if (Plugin.ObjectTable.LocalPlayer != null)
            {
                PacketDispatcher.HandleActorControlPacket(Plugin.ObjectTable.LocalPlayer.EntityId, 54, 1, 0, 0, 0, 0, 0, 0, 0, 0xE0000000, false);
            }
        }
        catch (Exception e)
        {
            AnoMech.Core.DiagnosticLog.Warn($"[ZoneGuard] Restoring targetability threw: {e}");
        }
    }

    // Opens the Social agent, which issues its own (callback-routed) party-member
    // request and processes the reply into the party HUD — the step a bare RequestData
    // can't trigger. Firing this from the settled inn state mirrors a manual open.
    private void OpenSocialForPartyResync()
    {
        var am = AgentModule.Instance();
        var social = am != null ? am->GetAgentByInternalId(AgentId.Social) : null;
        if (social == null) return;
        autoCloseSocial = true;
        social->Show();
        Plugin.Log.Information("[ZoneSession] Opened Social for party resync.");
    }

    // Closes the Social window again as soon as it finishes opening — but only when
    // we opened it (autoCloseSocial), so a manual open is left alone.
    private void OnSocialPostSetup(AddonEvent type, AddonArgs args)
    {
        if (!autoCloseSocial) return;
        autoCloseSocial = false;

        var am = AgentModule.Instance();
        var s = am != null ? am->GetAgentByInternalId(AgentId.Social) : null;
        if (s != null) s->Hide();
        Plugin.Log.Information("[ZoneSession] Auto-closed Social after party resync.");
    }

    // Dalamud's SafetyHook backend throws when it cannot patch the function; callers read
    // IsEnabled instead.
    public void EnableFirewall()
    {
        try { sendPacketHook.Enable(); }
        catch (Exception e) { AnoMech.Core.DiagnosticLog.Warn($"[ZoneGuard] The send filter would not enable: {e.Message}"); }
        try { receivePacketHook.Enable(); }
        catch (Exception e) { AnoMech.Core.DiagnosticLog.Warn($"[ZoneGuard] The receive filter would not enable: {e.Message}"); }
    }

    // Send-side firewall alone, outside a session, for the debug menu's in-inn timeline tests:
    // nothing but the heartbeat leaves the client. A no-op during a session, where both hooks
    // are on already.
    private bool sendHoldActive;
    // Where the server last placed the character: the hold's start, or the latest zone-in during it.
    private Vector3? holdPosition;
    private bool holdSawZoning;

    public void HoldSendFirewall(bool hold)
    {
        // guardArmed covers the second between a Revert and the lift, which the guard owns.
        if (IsActive || guardArmed || hold == sendHoldActive) return;
        if (hold)
        {
            if (HoldBlockedReason() is { } blocked)
            {
                AnoMech.Core.DiagnosticLog.Warn($"[ZoneSession] Debug send hold refused: {blocked}.");
                return;
            }
            holdPosition = Plugin.ObjectTable.LocalPlayer?.Position;
            holdSawZoning = false;
            try { sendPacketHook.Enable(); }
            catch (Exception e) { AnoMech.Core.DiagnosticLog.Warn($"[ZoneSession] The send filter would not enable: {e.Message}"); }
        }
        else
        {
            // No move made during the hold reached the server: put the character back where the
            // server last placed it, or the next movement packet reports a jump. Not while a
            // zone-in is placing it (or placed it with no character to re-anchor on, which then
            // could not have moved), nor once something else took the hook down (the server saw
            // the rest).
            if (!Zoning() && !holdSawZoning && sendPacketHook.IsEnabled && holdPosition is { } at
                && Plugin.ObjectTable.LocalPlayer is { } player && Vector3.Distance(player.Position, at) > LiftPositionTolerance)
                SetLocalPlayerPosition(at);
            try { sendPacketHook.Disable(); }
            catch (Exception e) { AnoMech.Core.DiagnosticLog.Warn($"[ZoneSession] The send filter would not disable: {e.Message}"); }
        }
        sendHoldActive = sendPacketHook.IsEnabled;
        AnoMech.Core.DiagnosticLog.Info(sendHoldActive == hold
            ? $"[ZoneSession] Send firewall {(hold ? "held: only the heartbeat leaves the client" : "released")} (debug hold, no session active)."
            : $"[ZoneSession] Send firewall NOT {(hold ? "held" : "released")}: the hook would not change (debug hold).");
    }

    // True once both filters are down. The receive side goes first and a refusal stops there, so
    // a lift that fails leaves the send filter up: nothing the client does reaches the server.
    public bool DisableFirewall()
    {
        try { receivePacketHook.Disable(); }
        catch (Exception e) { AnoMech.Core.DiagnosticLog.Warn($"[ZoneGuard] The receive filter would not disable: {e.Message}"); }
        if (!receivePacketHook.IsEnabled)
        {
            try { sendPacketHook.Disable(); }
            catch (Exception e) { AnoMech.Core.DiagnosticLog.Warn($"[ZoneGuard] The send filter would not disable: {e.Message}"); }
        }
        // A debug hold the lift just took down is over too, or the next hold would find it "on".
        sendHoldActive = false;
        return !sendPacketHook.IsEnabled && !receivePacketHook.IsEnabled;
    }

    // ── Zone loading sequence (mirrors Hyperborea Utils.LoadZone) ─────────────

    private void LoadZoneInternal(uint territory, bool unloading, Vector3 playerPos, float? rotation = null)
    {
        completedLoad = 0;
        var eventFramework = EventFramework.Instance();
        var gm = GameMain.Instance();
        Plugin.Log.Information($"[ZoneSession] LoadZone territory={territory} ef={((nint)eventFramework):X} gm={((nint)gm):X}");
        if (eventFramework == null || gm == null)
        {
            Plugin.Log.Error("[ZoneSession] Null singleton — aborting zone load");
            return;
        }

        var player = (Character*)Plugin.ObjectTable.LocalPlayer!.Address;
        if (player == null)
        {
            Plugin.Log.Error("[ZoneSession] Plugin.ObjectTable.LocalPlayer was null.");
        }

        var classJobId = (byte)Plugin.PlayerState.ClassJob.RowId;

        Plugin.Log.Information("[ZoneSession] Step 1: FinalizeInstanceContent");
        if (loadedInstanceContent != null)
        {
            var uiState = UIState.Instance();

            if (uiState != null)
            {
                uiState->DirectorTodo.IsShown = false;
            }

            EventFrameworkPointers.TerminateDirector(eventFramework, 0x80030000 + loadedInstanceContent.Value);
            loadedInstanceContent = null;

            ResetSync(uiState, player, classJobId);
        }

        Plugin.Log.Information("[ZoneSession] Step 2: DisableDraw all objects");
        foreach (var obj in Plugin.ObjectTable)
        {
            if (obj.Address == IntPtr.Zero) continue;
            ((FFXIVClientStructs.FFXIV.Client.Game.Object.GameObject*)obj.Address)->DisableDraw();
        }

        if (!unloading)
        {
            Plugin.Log.Information("[ZoneSession] Step 3: InitDirector");

            var cfc = GetContentFinderCondition(territory)!.Value;

            var contentId = cfc.Content.RowId;
            Plugin.Log.Information($"[ZoneSession] ContentId={contentId}");

            EventFrameworkPointers.InitDirector(eventFramework, 0x80030000 + contentId, contentId, 0);

            loadedInstanceContent = contentId;
            InstanceContentDirectorHelper.SetDutyData(cfc);

            SetSync(cfc, player, territory, classJobId);
        }
        else
        {
            Plugin.Log.Information("[ZoneSession] Step 3: InitDirector (Skipped)");
        }

        Plugin.Log.Information("[ZoneSession] Step 4: LoadZone (native)");
        GameMainPointers.LoadZone(gm, territory, 0, 0, 1);

        Plugin.Log.Information("[ZoneSession] Step 5: SetupTerritoryType");
        eventFramework->SetTerritoryTypeId((ushort)territory);

        // Dalamud's own territory is moved by Enter/Revert, around the guard, not here.
        Plugin.Log.Information("[ZoneSession] Step 6: SetPosition");
        SetLocalPlayerPosition(playerPos, rotation);

        Plugin.Log.Information("[ZoneSession] LoadZone complete");
        completedLoad = territory;
    }

    private void SetLocalPlayerPosition(Vector3 position, float? rotation = null)
    {
        if (Plugin.ObjectTable.LocalPlayer is { Address: var addr } && addr != IntPtr.Zero)
        {
            var chara = (Character*)addr;
            chara->GameObject.SetPosition(position.X, position.Y, position.Z);

            if (rotation != null)
            {
                chara->GameObject.SetRotation(rotation.Value);
            }
        }
    }

    private ContentFinderCondition? GetContentFinderCondition(uint territoryId)
    {
        var sheet = Plugin.DataManager.GetExcelSheet<TerritoryType>();

        if (sheet == null)
        {
            Plugin.Log.Debug($"[ZoneSession.GetContentFinderCondition] TerritoryType sheet was null.");
            return null;
        }

        var rowRef = sheet[territoryId].ContentFinderCondition;

        if (!rowRef.IsValid)
        {
            Plugin.Log.Debug($"TerritoryType sheet, index {territoryId} does not have a valid ContentFinderCondition reference.");
            return null;
        }

        return rowRef.Value;
    }

    // Dalamud only moves ClientState.TerritoryType on a server ZoneInit, which a client-side load
    // never gets, so plugins that gate on it (Splatoon's zone locks and script territories) keep
    // seeing the inn. Plugins hold a scoped proxy whose TerritoryType has no setter; the setter
    // is on the service it wraps, and it raises TerritoryChanged like a real zone-in.
    private static bool TrySetClientTerritory(uint territory)
    {
        try
        {
            object proxy = Plugin.ClientState;
            var service = proxy.GetType()
                .GetField("clientStateService", BindingFlags.NonPublic | BindingFlags.Instance)
                ?.GetValue(proxy) ?? proxy;
            var setter = service.GetType()
                .GetProperty("TerritoryType", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance)
                ?.GetSetMethod(nonPublic: true);
            if (setter == null)
            {
                AnoMech.Core.DiagnosticLog.Warn($"[ZoneSession] No TerritoryType setter on {service.GetType().FullName}; Dalamud keeps reading {Plugin.ClientState.TerritoryType}.");
                return false;
            }
            setter.Invoke(service, [territory]);
            return Plugin.ClientState.TerritoryType == territory;
        }
        catch (Exception e)
        {
            AnoMech.Core.DiagnosticLog.Warn($"[ZoneSession] Could not set Dalamud's TerritoryType to {territory}: {e}");
            return false;
        }
    }

    // (Item) Level Sync
    private void SetSync(ContentFinderCondition cfc, Character* player, uint territory, byte classJobId)
    {
        var cfcLevelSync = cfc.ClassJobLevelSync;

        if (sessionSave.LevelSync)
        {
            var currentLevel = (byte)Plugin.PlayerState.Level;
            var levelSynced = currentLevel > cfcLevelSync;

            if (levelSynced)
            {
                if (player != null)
                {
                    player->Level = cfcLevelSync;
                }

                var updateClassInfoPacket = new UpdateClassInfoPacket
                {
                    ClassJobId = classJobId,
                    CurrentLevel = currentLevel,
                    ClassJobLevel = currentLevel,
                    SyncedLevel = cfcLevelSync,
                    ClassJobExp = 0,
                    BaseRestedExperience = 0
                };

                PacketDispatcherPointers.HandleUpdateClassInfoPacket(0, &updateClassInfoPacket);
            }
        }

        if (sessionSave.ItemLevelSync)
        {
            var uiState = UIState.Instance();
            if (uiState != null)
            {
                var ilvlSync = cfc.ItemLevelSync != 0 ? cfc.ItemLevelSync : cfc.ItemLevelRequired;

                if (ilvlSync != 0)
                {
                    Plugin.Log.Debug($"Setting up iLvl sync to {ilvlSync}");
                    var syncedAttributes = GetSyncedAttributes(cfcLevelSync, ilvlSync);

                    foreach (var (baseParamId, value) in syncedAttributes)
                    {
                        sessionSave.Attributes[baseParamId] = uiState->PlayerState.Attributes[baseParamId];
                        uiState->PlayerState.Attributes[baseParamId] = value;
                    }
                }
            }
        }
    }

    private void ResetSync(UIState* uiState, Character* player, byte classJobId)
    {
        if (sessionSave.LevelSync)
        {
            var updateClassInfoPacket = new UpdateClassInfoPacket
            {
                ClassJobId = classJobId,
                CurrentLevel = (ushort)sessionSave.Level,
                ClassJobLevel = (ushort)sessionSave.Level,
                SyncedLevel = 0,
                ClassJobExp = (ushort)sessionSave.Exp,
                BaseRestedExperience = sessionSave.RestedExp
            };

            PacketDispatcherPointers.HandleUpdateClassInfoPacket(0, &updateClassInfoPacket);

            if (player != null)
            {
                player->Level = (byte)sessionSave.Level;
            }
        }

        if (sessionSave.ItemLevelSync && uiState != null)
        {
            foreach (var (baseParamId, value) in sessionSave.Attributes)
            {
                uiState->PlayerState.Attributes[baseParamId] = value;
            }
        }
    }

    private Dictionary<int, int> GetSyncedAttributes(byte level, ushort ilvl)
    {
        var stats = new Dictionary<int, int>();

        var itemSheet = Plugin.DataManager.GetExcelSheet<Item>();
        var baseParamSheet = Plugin.DataManager.GetExcelSheet<BaseParam>();
        var paramGrowSheet = Plugin.DataManager.GetExcelSheet<ParamGrow>();

        var supportedAttributes = new PlayerAttribute[]
        {
                PlayerAttribute.SkillSpeed,
                PlayerAttribute.SpellSpeed
        };

        foreach (var attribute in supportedAttributes)
        {
            switch (attribute)
            {
                case PlayerAttribute.SkillSpeed:
                case PlayerAttribute.SpellSpeed:
                    stats[(int)attribute] = paramGrowSheet[level].BaseSpeed;
                    break;
                default:
                    continue;
            }
        }

        // Get Item Stats
        var inventoryManager = InventoryManager.Instance();
        var equippedItems = inventoryManager->GetInventoryContainer(InventoryType.EquippedItems);

        for (int i = 0; i < equippedItems->GetSize(); i++)
        {
            var inventoryItem = equippedItems->Items[i];
            var itemId = inventoryItem.ItemId;

            if (itemId == 0)
            {
                continue;
            }

            var item = itemSheet[itemId];
            var itemLevel = item.LevelItem.RowId;

            if (item.LevelItem.RowId <= ilvl) // Add it as is if the ilvl is the same or less than sync
            {
                Plugin.Log.Debug($"Item \"{item.Name}\" (ilvl {item.LevelItem.RowId}) fits the ilvl sync requirements.");

                for (int x = 0; x < item.BaseParam.Count; x++)
                {
                    var baseParam = item.BaseParam[x];
                    var baseParamId = (int)baseParam.RowId;

                    if (!supportedAttributes.Contains((PlayerAttribute)baseParamId))
                    {
                        continue;
                    }

                    stats[baseParamId] += item.BaseParamValue[x];
                }

                // Add extra stats
                ApplyExtraStats(stats, GetMateriaStats(inventoryItem));
                ApplyExtraStats(stats, GetMandervilleWeaponStats(inventoryItem));
            }
            else // Calculate the sync value
            {
                var resistanceStats = new Dictionary<int, int>();

                var resistanceSheet = Plugin.DataManager.GetExcelSheet<ResistanceWeaponAdjust>();
                if (resistanceSheet.TryGetRow(itemId, out var _))
                {
                    resistanceStats = GetMateriaStats(inventoryItem);
                }

                var mandervilleStats = GetMandervilleWeaponStats(inventoryItem);

                // Doing this instead of calling ExdModule.GetItemRowById because it's not guaranteed to always return on this frame
                var dummyItem = new byte[0xA0];
                fixed (byte* dummyItemPtr = dummyItem)
                {
                    *(dummyItemPtr + 0x54) = item.BaseParamModifier;
                    *(ushort*)(dummyItemPtr + 0x8A) = ilvl;
                    *(dummyItemPtr + 0x9A) = (byte)item.EquipSlotCategory.RowId;

                    for (int x = 0; x < item.BaseParam.Count; x++)
                    {
                        var baseParam = item.BaseParam[x];
                        var baseParamId = (int)baseParam.RowId;

                        if (!supportedAttributes.Contains((PlayerAttribute)baseParamId))
                        {
                            continue;
                        }

                        var statValue = item.BaseParamValue[x];

                        if (resistanceStats.TryGetValue(baseParamId, out var resistanceStat))
                        {
                            statValue += (short)resistanceStat;
                        }

                        if (mandervilleStats.TryGetValue(baseParamId, out var mandervilleStat))
                        {
                            statValue += (short)mandervilleStat;
                        }

                        var statMaxValue = (int)InventoryItem.GetParameterMaxValue((uint)baseParamId, dummyItemPtr);
                        var syncedValue = int.Min(statValue, statMaxValue);
                        stats[baseParamId] += syncedValue;

                        Plugin.Log.Debug($"Item \"{item.Name}\" (ilvl {item.LevelItem.RowId})'s {(PlayerAttribute)baseParamId} was synced to {syncedValue}");
                    }
                }
            }
        }

        // Get Food Buffs
        var localPlayer = (BattleChara*)Plugin.ObjectTable.LocalPlayer!.Address;

        if (localPlayer != null)
        {
            var statusManager = localPlayer->StatusManager;

            foreach (var status in statusManager.Status)
            {
                var statusId = status.StatusId;

                if (statusId == 0 || statusId != 48)
                {
                    continue;
                }

                var hq = status.Param > 10000;
                var foodId = hq ? status.Param - 10000 : status.Param;

                if (!Plugin.DataManager.GetExcelSheet<ItemFood>().TryGetRow((uint)foodId, out var food))
                {
                    continue;
                }

                foreach (var bonus in food.Params)
                {
                    var stat = (int)bonus.BaseParam.RowId;

                    if (stat == 0 || !stats.ContainsKey(stat))
                    {
                        continue;
                    }

                    var value = hq ? bonus.ValueHQ : bonus.Value;
                    var max = hq ? bonus.MaxHQ : bonus.Max;
                    int statBuff;

                    if (bonus.IsRelative)
                    {
                        var currentStat = stats[stat];
                        var percentBuff = (int)(currentStat * (value / 100f));
                        statBuff = int.Min(percentBuff, max);
                    }
                    else
                    {
                        statBuff = value;
                    }

                    stats[stat] += statBuff;
                }
            }
        }

        return stats;
    }

    // This also works for Resistance Weapons
    private Dictionary<int, int> GetMateriaStats(InventoryItem inventoryItem)
    {
        var stats = new Dictionary<int, int>();
        var materiaSheet = Plugin.DataManager.GetExcelSheet<Materia>();

        for (int i = 0; i < inventoryItem.Materia.Length; i++)
        {
            var materiaId = inventoryItem.Materia[i];

            if (materiaId == 0 || !materiaSheet.TryGetRow(materiaId, out var materiaRow))
            {
                continue;
            }

            var index = inventoryItem.MateriaGrades[i];
            var statValue = materiaRow.Value[index];
            var stat = materiaRow.BaseParam.RowId;
            stats[(int)stat] = statValue;
        }

        return stats;
    }

    // https://github.com/VioletStardustXIV/XivGearExport/blob/main/XivGearExport/XivGearSet.cs#L447
    private Dictionary<int, int> GetMandervilleWeaponStats(InventoryItem inventoryItem)
    {
        var stats = new Dictionary<int, int>();

        var statsSheet = Plugin.DataManager.GetExcelSheet<MandervilleWeaponEnhance>();
        var materiaSheet = Plugin.DataManager.GetExcelSheet<Materia>();

        if (!statsSheet.TryGetRow(inventoryItem.ItemId, out var _))
        {
            return stats;
        }

        for (int i = 0; i < inventoryItem.Materia.Length; i++)
        {
            var materiaId = inventoryItem.Materia[i];

            if (materiaId == 0 || !materiaSheet.TryGetRow(materiaId, out var materiaRow))
            {
                continue;
            }

            var index = inventoryItem.MateriaGrades[i];
            var statValue = materiaRow.Value[index];

            switch (materiaId)
            {
                case 1403:
                    stats[(int)PlayerAttribute.CriticalHit] = statValue;
                    break;
                case 1404:
                    stats[(int)PlayerAttribute.DirectHitRate] = statValue;
                    break;
                case 1405:
                    stats[(int)PlayerAttribute.Determination] = statValue;
                    break;
                case 1406:
                    stats[(int)PlayerAttribute.SkillSpeed] = statValue;
                    break;
                case 1407:
                    stats[(int)PlayerAttribute.SpellSpeed] = statValue;
                    break;
                case 1408:
                    stats[(int)PlayerAttribute.Tenacity] = statValue;
                    break;
                case 1409:
                    stats[(int)PlayerAttribute.Piety] = statValue;
                    break;
            }
        }

        return stats;
    }

    private void ApplyExtraStats(Dictionary<int, int> stats, Dictionary<int, int> extraStats)
    {
        foreach (var (attribute, value) in extraStats)
        {
            if (!stats.ContainsKey(attribute))
            {
                continue;
            }

            stats[attribute] += value;
        }
    }

    // ── Packet firewall detours (mirrored from Hyperborea Memory.cs) ──────────

    private byte SendPacketDetour(nint a1, nint a2, nint a3, byte a4)
    {
        const byte defaultReturn = 1;
        if (a2 == IntPtr.Zero) return defaultReturn;
        try
        {
            var opcode = *(ushort*)a2;
            if (opcode == heartbeatOpcode)
                return sendPacketHook.Original(a1, a2, a3, a4);
            heldOutbound.AddOrUpdate(opcode, 1, (_, held) => held + 1);
        }
        catch (Exception e)
        {
            Plugin.Log.Error($"[ZoneSession] SendPacketDetour: {e.Message}");
            return defaultReturn;
        }
        return defaultReturn;
    }

    private void ReceivePacketDetour(PacketDispatcher* a1, uint a2, nint a3)
    {
        if (a3 == IntPtr.Zero) return;
        dispatcher = a1;
        var incomingOpcode = *(ushort*)(a3 + 2);
        if (incomingOpcode is ActionEffect1Opcode or ActionEffect8Opcode)
        {
            var counter = *(uint*)(a3 + 0x10 + 0xC);
            if (counter > MaxActionEffectCounter) MaxActionEffectCounter = counter;
        }
        try
        {
            // Release builds always run the firewall (safe mode hardcoded on).
            // Debug builds honour the config toggle so it can be flipped off
            // for testing without affecting shipped behaviour.
#if DEBUG
            var safeMode = Plugin.Config.SafeMode;
#else
            const bool safeMode = true;
#endif
            if (!safeMode || Plugin.Config.ZoneDownOpcodes.Contains(incomingOpcode))
                receivePacketHook.Original(a1, a2, a3);
            else
                System.Threading.Interlocked.Increment(ref heldInbound);
        }
        catch (Exception e)
        {
            Plugin.Log.Error($"[ZoneSession] ReceivePacketDetour: {e.Message}");
        }
    }

    // Feeds one server-style packet to the client through the same entry the real ones take,
    // bypassing the firewall: a byte-identical replay of a captured packet, for handlers
    // FFXIVClientStructs doesn't expose. `body` is the IPC payload after the 16-byte header
    // built here; `sourceEntityId` is the actor the packet is about. Needs a real packet to
    // have passed the hook first (the heartbeat guarantees one within seconds of login).
    public bool InjectIncomingPacket(uint sourceEntityId, ushort opcode, ReadOnlySpan<byte> body, string what)
    {
        if (dispatcher == null)
        {
            AnoMech.Core.DiagnosticLog.Warn($"[ZoneSession] InjectIncomingPacket({what}): no PacketDispatcher captured yet -- dropped.");
            return false;
        }
        var buffer = new byte[16 + body.Length];
        BitConverter.TryWriteBytes(buffer.AsSpan(0, 2), (ushort)0x14);
        BitConverter.TryWriteBytes(buffer.AsSpan(2, 2), opcode);
        BitConverter.TryWriteBytes(buffer.AsSpan(8, 4), (uint)DateTimeOffset.UtcNow.ToUnixTimeSeconds());
        body.CopyTo(buffer.AsSpan(16));
        AnoMech.Core.DiagnosticLog.Info($"[ZoneSession] InjectIncomingPacket({what}): opcode=0x{opcode:X4} source=0x{sourceEntityId:X} len={body.Length}.");
        fixed (byte* p = buffer)
        {
            receivePacketHook.Original(dispatcher, sourceEntityId, (nint)p);
        }
        return true;
    }

    // ── Lifecycle ─────────────────────────────────────────────────────────────

    public void Dispose()
    {
        Plugin.AddonLifecycle.UnregisterListener(AddonEvent.PostSetup, "Social", OnSocialPostSetup);

        // To not freeze a player that's disabling/reloading/etc the plugin while not in a Scenario
        if (IsActive)
        {
            Revert(true);
        }
        else
        {
            // The 1s lift after a Revert may still be pending, position re-assert included.
            if (guardArmed)
            {
                SetLocalPlayerPosition(armedPosition, armedRotation);
                ReleasePlayerConditions();
                LiftFirewallOrDie("on plugin unload during the post-revert wait", mayRetry: false);
            }
            // Through its own release, which puts the character back first.
            HoldSendFirewall(false);
            DisableFirewall(); // To be sure the Hooks are disabled before calling Dispose
        }

        if (Current == this) Current = null;
        sendPacketHook.Dispose();
        receivePacketHook.Dispose();
    }
}
